kao-api:
  build: .
  volumes: 
   # プログラム変更するたびにビルドしなくて良いようにローカルファイルをボリュームマウントする
    - "./src:/opt/tensor-api"
    - "./data:/opt/tensor-api/data"
nginx:
  build: ./nginx
  volumes_from:
    - kao-api
  ports:
    - "8080:8080"